server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: core-services
          uri: lb://core-services
          predicates:
            - Path=/users/**,/bank-accounts/**,/utility-accounts/**,/transactions/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: fund-transfer-service
          uri: lb://fund-transfer-service
          predicates:
            - Path=/api/fund-transfers/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8571/realms/banking-service

